### ISSUE TITLE
is this working in the current version of the steam game?

### ISSUE THREAD

**Issue by mben67** [MajorZero69/mgs3-trainer#1]

**Comment by MajorZero69** [comment]
No, I didn't know anyone was actually trying to use it so I've had no urgency to update it to 1.5.1. I'll update it today.

**Comment by MajorZero69** [comment]
The trainer has been updated to support v1.5.1 of MGS3. Hopefully you like it :)

**Comment by MajorZero69** [comment]
The trainer has been updated to support v1.5.1 of MGS3. Hopefully you like it :)

**Comment by mben67** [comment]
> The trainer has been updated to support v1.5.1 of MGS3. Hopefully you like it :)

thanks a lot!
